"""Procedural vessel-mesh generation for testing guidewire navigation.

Two static "vessel" meshes are provided:

* :func:`straight_tube`  – a hollow cylinder the rod is threaded through.
* :func:`s_tube`         – an S-shaped tube built from two opposite circular
  arcs (default 60 deg each) at a prescribed bend radius, mimicking a tortuous
  vascular segment.

Both are open-ended tube *walls* (no end caps) so a rod can be inserted from
either end.  Meshes are generated by sweeping a circular cross-section along a
centreline using rotation-minimising frames (double-reflection method) so the
tube does not accumulate spurious twist around its own axis.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class TriMesh:
    """A triangle mesh: ``vertices`` (N,3) float32, ``faces`` (M,3) int32."""

    vertices: np.ndarray
    faces: np.ndarray
    # centreline used to build the tube (K,3); handy for placing the rod.
    centerline: np.ndarray | None = None

    @property
    def n_vertices(self) -> int:
        return int(self.vertices.shape[0])

    @property
    def n_faces(self) -> int:
        return int(self.faces.shape[0])

    def save_obj(self, path: str) -> None:
        with open(path, "w") as f:
            f.write("# generated by sim_fold_ipc.meshes\n")
            for v in self.vertices:
                f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
            for tri in self.faces:
                # OBJ is 1-indexed
                f.write(f"f {tri[0] + 1} {tri[1] + 1} {tri[2] + 1}\n")


# --------------------------------------------------------------------------- #
# centreline construction
# --------------------------------------------------------------------------- #
def _rodrigues(v: np.ndarray, axis: np.ndarray, angle: float) -> np.ndarray:
    """Rotate vector(s) ``v`` about unit ``axis`` by ``angle`` (Rodrigues)."""
    axis = axis / np.linalg.norm(axis)
    c, s = np.cos(angle), np.sin(angle)
    return (
        v * c
        + np.cross(axis, v) * s
        + axis * (axis @ v.T).reshape(-1, 1) * (1.0 - c)
        if v.ndim == 2
        else v * c + np.cross(axis, v) * s + axis * (axis @ v) * (1.0 - c)
    )


def _arc_centerline(
    p0: np.ndarray,
    t0: np.ndarray,
    turn_axis: np.ndarray,
    sweep_angle: float,
    radius: float,
    n: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Points along a circular arc.

    Returns (points[n,3], end_point, end_tangent). ``sweep_angle`` may be
    signed: its sign together with ``turn_axis`` sets the turn direction.
    """
    t0 = t0 / np.linalg.norm(t0)
    turn_axis = turn_axis / np.linalg.norm(turn_axis)
    # direction from p0 towards the arc centre (perpendicular to t0)
    to_center = np.cross(turn_axis, t0)
    to_center /= np.linalg.norm(to_center)
    center = p0 + radius * np.sign(sweep_angle if sweep_angle != 0 else 1.0) * to_center
    r_vec = p0 - center
    thetas = np.linspace(0.0, sweep_angle, n)
    pts = np.array([center + _rodrigues(r_vec, turn_axis, th) for th in thetas])
    end_t = _rodrigues(t0, turn_axis, sweep_angle)
    return pts, pts[-1], end_t / np.linalg.norm(end_t)


def _straight_centerline(
    p0: np.ndarray, t0: np.ndarray, length: float, n: int
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    t0 = t0 / np.linalg.norm(t0)
    s = np.linspace(0.0, length, n)
    pts = p0[None, :] + s[:, None] * t0[None, :]
    return pts, pts[-1], t0


def _dedup_join(chunks: list[np.ndarray]) -> np.ndarray:
    """Concatenate centreline chunks, dropping duplicated join points."""
    out = [chunks[0]]
    for c in chunks[1:]:
        out.append(c[1:])
    return np.concatenate(out, axis=0)


# --------------------------------------------------------------------------- #
# sweeping a circular cross-section along a centreline
# --------------------------------------------------------------------------- #
def _rmf_frames(points: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Rotation-minimising normal/binormal frames along a polyline.

    Double-reflection method (Wang et al. 2008). Returns (normals, binormals),
    each (K,3), orthonormal to the local tangent.
    """
    k = len(points)
    tangents = np.zeros_like(points)
    tangents[:-1] = points[1:] - points[:-1]
    tangents[-1] = tangents[-2]
    tangents /= np.linalg.norm(tangents, axis=1, keepdims=True)

    # seed normal perpendicular to the first tangent
    ref = np.array([0.0, 1.0, 0.0])
    if abs(tangents[0] @ ref) > 0.9:
        ref = np.array([1.0, 0.0, 0.0])
    normals = np.zeros_like(points)
    normals[0] = ref - (ref @ tangents[0]) * tangents[0]
    normals[0] /= np.linalg.norm(normals[0])

    for i in range(k - 1):
        v1 = points[i + 1] - points[i]
        c1 = v1 @ v1
        if c1 < 1e-20:
            normals[i + 1] = normals[i]
            continue
        n_l = normals[i] - (2.0 / c1) * (v1 @ normals[i]) * v1
        t_l = tangents[i] - (2.0 / c1) * (v1 @ tangents[i]) * v1
        v2 = tangents[i + 1] - t_l
        c2 = v2 @ v2
        if c2 < 1e-20:
            normals[i + 1] = n_l
        else:
            normals[i + 1] = n_l - (2.0 / c2) * (v2 @ n_l) * v2
        normals[i + 1] /= np.linalg.norm(normals[i + 1])

    binormals = np.cross(tangents, normals)
    binormals /= np.linalg.norm(binormals, axis=1, keepdims=True)
    return normals, binormals


def sweep_tube(
    centerline: np.ndarray,
    radius: float,
    n_theta: int = 24,
) -> TriMesh:
    """Sweep a circle of ``radius`` along ``centerline`` -> open tube wall.

    Faces are wound so their normals point *outward* (away from the axis).
    """
    normals, binormals = _rmf_frames(centerline)
    k = len(centerline)
    thetas = np.linspace(0.0, 2.0 * np.pi, n_theta, endpoint=False)
    cos_t, sin_t = np.cos(thetas), np.sin(thetas)

    verts = np.zeros((k * n_theta, 3), dtype=np.float32)
    for i in range(k):
        ring = (
            centerline[i][None, :]
            + radius * (cos_t[:, None] * normals[i][None, :]
                        + sin_t[:, None] * binormals[i][None, :])
        )
        verts[i * n_theta:(i + 1) * n_theta] = ring

    faces = []
    for i in range(k - 1):
        for j in range(n_theta):
            jn = (j + 1) % n_theta
            a = i * n_theta + j
            b = i * n_theta + jn
            c = (i + 1) * n_theta + j
            d = (i + 1) * n_theta + jn
            # outward-facing winding (normals point away from the axis)
            faces.append((a, b, c))
            faces.append((b, d, c))
    faces = np.asarray(faces, dtype=np.int32)
    return TriMesh(vertices=verts, faces=faces, centerline=centerline.astype(np.float32))


# --------------------------------------------------------------------------- #
# public mesh builders
# --------------------------------------------------------------------------- #
def straight_tube(
    length: float = 0.20,
    radius: float = 0.004,
    n_axial: int = 60,
    n_theta: int = 24,
    axis: str = "z",
) -> TriMesh:
    """A hollow straight cylinder of inner ``radius`` and ``length`` (metres)."""
    dir_map = {"x": [1, 0, 0], "y": [0, 1, 0], "z": [0, 0, 1]}
    t0 = np.array(dir_map[axis], dtype=float)
    pts, _, _ = _straight_centerline(np.zeros(3), t0, length, n_axial + 1)
    return sweep_tube(pts, radius, n_theta)


def s_tube(
    radius: float = 0.004,
    bend_radius: float = 0.03,
    bend_angle_deg: float = 60.0,
    straight_len: float = 0.04,
    n_theta: int = 24,
    seg_res: int = 40,
) -> TriMesh:
    """An S-shaped tube: straight, +bend, -bend, straight.

    ``bend_angle_deg`` is the turn of *each* arc (default 60 deg); ``bend_radius``
    is the centreline radius of curvature of the bends.
    """
    ang = np.deg2rad(bend_angle_deg)
    turn_axis = np.array([0.0, 1.0, 0.0])  # bends live in the X-Z plane
    p = np.zeros(3)
    t = np.array([0.0, 0.0, 1.0])

    c0, p, t = _straight_centerline(p, t, straight_len, seg_res)
    c1, p, t = _arc_centerline(p, t, turn_axis, +ang, bend_radius, seg_res)
    c2, p, t = _arc_centerline(p, t, turn_axis, -ang, bend_radius, seg_res)
    c3, p, t = _straight_centerline(p, t, straight_len, seg_res)

    centerline = _dedup_join([c0, c1, c2, c3])
    return sweep_tube(centerline, radius, n_theta)
